import 'package:flutter/material.dart';

class AppColor {
  Color primaryColor = const Color(0xff7D7AFF);
  Color primaryLiteColor = const Color(0xff9B9CFF);
  Color primaryLightColor = const Color(0xff091932);
  Color secondaryColor = const Color(0xffD6E8CE);
  Color secondaryGreenColor = const Color(0xff5CFF9D);
  Color primaryDark = const Color(0xff1E232C);
  Color primaryBgColor = const Color(0xff111827);
  Color primaryBackGroundColor = const Color(0xff060D18);
  Color bgDark = const Color(0xff1F252F);
  Color walletColor = const Color(0xffA381FF);
  Color dashboardColor = const Color(0xff050B15);
  Color primaryWhite = const Color(0xffffffff);
  Color primaryYellow = const Color(0xffF29528);
  Color primaryRed = const Color(0xffFF2E2E);
  Color primaryGreen = const Color(0xff00AD45);
  Color primaryMenu = const Color(0xff283C5C);
  Color textPrimary = const Color(0xff008585);
  Color textFieldColor = const Color(0xffF7F8F9);
  Color hintTextColor = const Color(0xff8391A1);
  Color darkGrey = const Color(0xff6A707C);
  Color secondaryGreen = const Color(0xff38656A);
  Color lightItemsColor = const Color(0xff9B9B9B);
  Color greyOne = const Color(0xffF5F5F5);
  Color greyTwo = const Color(0xffE0E0E0);
  Color greySix = const Color(0xff8F8F8F);
  Color greyEight = const Color(0xff666666);
  Color referral = const Color(0xff1F242C);
  Color darkItemsColor = const Color(0xff222222);
  Color pureBlackColor = const Color(0xff000000);
  Color lightBlue = const Color(0xffBCEBF0);
  Color lightBlack = const Color(0xffEFF1F0);
  Color containerGreen = const Color(0xffCCE8E7);
  Color logout = const Color(0xffFF897D);
  Color limeSecondary = const Color(0xff66F7F7);
  Color uploadImage = const Color(0xffEAF1FF);
  Color cartColor = const Color(0xffEAF1FF);
  Color chartGreenColor = const Color(0xff00BEBE);
  Color chartGreyColor = const Color(0xff4B607C);
  Color ratingColor = const Color(0xff41DBDA);
  Color descBgColor = const Color(0xffEAF1FF);
  Color overviewButton = const Color(0xffDAF6F5);
  Color overviewContainer = const Color(0xffF7F7F7);
  Color profileBackground = const Color(0xffF1FFFE);
}
